//
// This file is automatically generated.
//
// Don't edit this file!
//

import * as mod from "$ENTRYPOINT";
import {MikrokatServer} from "mikrokat";

let server=new MikrokatServer({mod: mod});

addEventListener("fetch", ev=>{
	ev.respondWith(server.handleRequest({
		request: ev.request
	}));
});


/*addEventListener("fetch", ev=>{
	ev.respondWith(new Response("hello"));
});*/
