import BaseTarget from "./BaseTarget.js";

let CLOUDFLARE_STUB=`
//
// This file is automatically generated.
//
// Don't edit this file!
//

import * as mod from "$ENTRYPOINT";
import {MikrokatServer} from "mikrokat";

let serverMap=new Map();

export default {
	async fetch(request, env, ctx) {
		if (!serverMap.get(env)) {
			serverMap.set(env,new MikrokatServer({mod: mod, env: env}));
		}

		let server=serverMap.get(env);
		return await server.handleRequest({request,ctx});
	}
}
`;

export default class CloudflareTarget extends BaseTarget {
	constructor(arg) {
		super(arg);
	}

	async build() {
		await this.cli.writeStub(".target/entrypoint.cloudflare.js",CLOUDFLARE_STUB);
	}

	async init() {
		await this.cli.updateJsonConfig("wrangler.json",async wrangler=>{
			if (!wrangler) wrangler={};
			wrangler.main=".target/entrypoint.cloudflare.js";

			if (!wrangler.build) wrangler.build={};
			wrangler.build.command="TARGET=cloudflare npx mikrokat build";

			return wrangler;
		});

		await this.cli.updateLineArrayConfig(".gitignore",async lines=>{
			if (!lines.includes(".target")) lines.push(".target");
			if (!lines.includes(".wrangler")) lines.push(".wrangler");
			return lines;
		});

		console.log("Cloudflare initialized. Start a dev server with:");
		console.log();
		console.log("  wrangler dev");
		console.log();
	}
}