import BaseTarget from "./BaseTarget.js";
import {Section} from '@ltd/j-toml';
import packageVersions from "../main/package-versions.js";

let FASTLY_STUB=`
//
// This file is automatically generated.
//
// Don't edit this file, and don't put it under version control!
//

import {MikrokatServer} from "mikrokat";

$VARS

let server=new MikrokatServer({
	target: "fastly",
	modules, 
	imports,
	fileContent,
	services,
	serviceClasses
});

addEventListener("fetch", ev=>{
	ev.respondWith(server.handleRequest({
		request: ev.request
	}));
});
`;

export default class FastlyTarget extends BaseTarget {
	constructor(arg) {
		super(arg);
	}

	async build() {
		await this.project.writeStub(".target/entrypoint.fastly.js",FASTLY_STUB);
	}

	async init() {
		await this.project.processProjectFile("package.json","json",async pkg=>{
			if (!pkg.scripts) pkg.scripts={};
			if (!pkg.scripts["dev:fastly"])
				pkg.scripts["dev:fastly"]="fastly compute serve";

			if (!pkg.scripts["deploy:fastly"])
				pkg.scripts["deploy:fastly"]="fastly compute publish";

			if (!pkg.dependencies) pkg.dependencies={};
			pkg.dependencies["@fastly/cli"]="^"+packageVersions["@fastly/cli"];
			pkg.dependencies["@fastly/js-compute"]="^"+packageVersions["@fastly/js-compute"];
		});

		let pkg=await this.project.processProjectFile("package.json","json");

		await this.project.processProjectFile("fastly.toml","toml",async fastly=>{
			if (!fastly)
				fastly={};

			fastly.name=pkg.name;
			fastly.language="javascript";

			if (!fastly.manifest_version)
				fastly.manifest_version=3;

			if (!fastly.scripts) fastly.scripts=Section({});
			fastly.scripts.build="TARGET=fastly npm run build && js-compute-runtime .target/entrypoint.fastly.js ./bin/main.wasm"

			return fastly;
		});

		await this.project.processProjectFile(".gitignore","lines",async ignore=>{
			if (!ignore.includes("bin")) ignore.push("bin");
			if (!ignore.includes("pkg")) ignore.push("pkg");
		});

		/*this.cli.log("Fastly initialized. Start a dev server with:");
		this.cli.log();
		this.cli.log("  npm run dev:fastly");
		this.cli.log();
		this.cli.log("Deploy with:");
		this.cli.log();
		this.cli.log("  npm run deploy:fastly");
		this.cli.log();*/
	}
}