import BaseTarget from "./BaseTarget.js";

let CLOUDFLARE_STUB=`
//
// This file is automatically generated.
//
// Don't edit this file!
//

import * as mod from "$ENTRYPOINT";
import {MikrokatServer} from "mikrokat";

let server=new MikrokatServer({mod: mod});

export default async function(request) {
	return await server.handleRequest({
		request: request
	});
}

export const config = { path: "/*" };
`;

export default class NetlifyTarget extends BaseTarget {
	constructor(arg) {
		super(arg);
	}

	async build() {
		console.log("Building mikrokat stub for netlify...");
		await this.cli.writeStub("netlify/edge-functions/entrypoint.netlify.js",CLOUDFLARE_STUB);
	}

	async init() {
		await this.cli.updateJsonConfig("package.json",async pkg=>{
			if (!pkg.scripts) pkg.scripts={};
			if (!pkg.scripts["dev:netlify"])
				pkg.scripts["dev:netlify"]="TARGET=netlify npx mikrokat build && netlify dev --cwd=."

			return pkg;
		});

		await this.cli.updateLineArrayConfig(".gitignore",async lines=>{
			if (!lines.includes(".netlify")) lines.push(".netlify");
			if (!lines.includes("netlify")) lines.push("netlify");
			return lines;
		});

		console.log("Netlify initialized. Start a dev server with:");
		console.log();
		console.log("  npm run dev:netlify");
		console.log();
	}
}